services:
  postgres:
    image: postgres:17
    container_name: security_postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d  # Auto-import SQL/CSV on startup
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - security_network

  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: security_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@security.com"
      PGADMIN_DEFAULT_PASSWORD: "Andrew123"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - security_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  security_network:
    driver: bridge